version: '3'

services:
  classy-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin123"
    ports:
      - "15432:5432"
    volumes:
      - /Users/feliperibeiro/docker/postgres:/var/lib/postgresql/data